from .barreleye import Barreleye
from .bird import Bird
from .catfish import Catfish
from .donkey import Donkey
from .duck import Duck
from .goat import Goat
from .goldfish import Goldfish
from .insect import Insect
from .king_cobra import King_Cobra
from .kingsnake import Kingsnake
from .llama import Llama
from .pig import Pig
from .sheep import Sheep
from .snake import Snake
from .whale import Whale
